gitのリビジョンを収集するように
kaz/pprotein pull request #7
Opened 2021-08-22 10:35 UTC by wtks

- `/home/isucon/.git-revision`からコミットハッシュを読み取って送るようにした
  - `make deploy`の最後に`.git-revision`を書き出す処理を書く
- gitリポジトリのディレクトリから直接取得するのは、実際にデプロイされてるバージョンが保証できないためやめた

.git-revisionの置き場所はパーミッションの問題でとりあえずisuconユーザーのホームディレクトリに置いたが、テストとかしづらいのでなんとかしたい(/tmpは再起動すると消える可能性があるから控えた)

2021-08-22 11:38 UTC, kaz requested changes
commit-hashを書き込んだファイルを別途用意する代わりに、リポジトリの位置を指定して `.git/HEAD` → `.git/refs/heads/****` を直接読みに行くのとかはどうですか？

2021-08-22 11:38 UTC, kaz commented on integration/integration.go
> +	r.Use(gitRevisionResponseMiddleware)
`integration/mux` では NewDebugHandler を呼ばず、RegisterDebugHandlers を直接呼び出すので、これは RegisterDebugHandlers の方でやりたいです。

2021-08-22 11:38 UTC, kaz commented on integration/integration.go
> +		revision, err := ioutil.ReadFile("/home/isucon/.git-revision")
環境変数とかで変えれるようにしたいです

2021-08-22 11:54 UTC, wtks commented
リポジトリ直接読みに行ってないのは、`make deploy`がそのリビジョンで成功してることを保証したいからなんですよね。

って思ったけど、`make deploy`成功しなかったり、し忘れてたらすぐ気づくかってなったので直接読み込むようにします。
`make deploy`を介さずにインスタンス内で直接gitコマンド叩いて作業するのは序盤の僕だけでしたし。

2021-09-12 05:51 UTC, wtks commented
直してみた

2021-09-12 06:44 UTC, kaz commented
プロ

2021-09-12 06:44 UTC, kaz approved these changes

2021-09-12 06:44 UTC, merged